package bkc

import (
	"strings"

	"github.com/spencerbull/yokai/internal/config"
)

func init() {
	register(
		// MiaAI Lab commit a0743929 switched the RTX PRO 6000 recipe to the
		// dense BF16 lm_head export on 2026-08-24. The packed-head profile
		// below remains available as a rollback so cached weights stay usable.
		Config{
			ID:       "qwen3-8-27b-nvfp4-bf16-lmhead-sglang-dflash2",
			Name:     "Qwen3.8 27B NVFP4 BF16 lm_head + DFlash2 (SGLang)",
			Workload: WorkloadSGLang,
			ModelID:  "RadixArk/Qwen3.8-27B-NVFP4-BF16-LMHead",
			Image:    imageSGLangQwen38DFlash2,
			Port:     "30000",
			ExtraArgs: strings.Join([]string{
				"sglang serve",
				"--trust-remote-code",
				"--revision 009632fef96dd349150baa780c984e62e70e91fe",
				"--served-model-name Qwen3.8-27B",
				"--tp-size 1",
				"--context-length 262144",
				"--mem-fraction-static 0.85",
				"--max-running-requests 8",
				"--cuda-graph-max-bs-decode 8",
				"--mamba-radix-cache-strategy extra_buffer_lazy",
				"--mamba-ssm-dtype bfloat16",
				"--kv-cache-dtype fp8_e4m3",
				"--attention-backend flashinfer",
				"--chunked-prefill-size 2048",
				"--reasoning-parser qwen3",
				"--tool-call-parser qwen3_coder",
				`--default-chat-template-kwargs {"enable_thinking":false}`,
				"--speculative-algorithm DFLASH",
				"--speculative-draft-model-path incoai/Qwen3.8-27B-DFlash2",
				"--speculative-draft-model-revision dedf8df68adfb1afeaf7b7480c0a0243108177b4",
				"--speculative-num-draft-tokens 8",
				"--enable-metrics",
			}, " "),
			Volumes: hfMountDefault,
			Runtime: config.RuntimeOptions{
				IPCMode: "host",
				ShmSize: "32g",
			},
			Description: "Qwen3.8 27B NVFP4 with a dense BF16 output head and DFlash2 speculative decoding on one RTX PRO 6000 Blackwell.",
			Source:      "MiaAI Lab RTX PRO 6000 recipe a0743929 + SGLang Qwen3.8 cookbook + RadixArk BF16 lm_head checkpoint",
			Notes: []string{
				"The dense BF16 lm_head export is the target used for the SGLang cookbook measurements; the transformer body remains NVFP4.",
				"The pinned checkpoint contains 23.76 GB of Hub blobs, about 1.83 GB more than the packed-head rollback.",
				"The image, DFlash2 drafter, 262,144-token context, and eight-request policy match the Finn-validated packed-head profile.",
				"extra_buffer_lazy is the intentional high-throughput Mamba cache tier; the extra_buffer alternative spends an additional state slot per request to favor latency.",
				"BF16 Mamba state passed the live smoke and throughput checks; workload-specific accuracy evaluation remains an open quality gate.",
				"Keep the packed-head DFlash2 or DSpark BKC available until this profile passes production quality and throughput checks.",
			},
			TargetDevices:   []string{DeviceRTXPRO6000},
			MinVRAMGBPerGPU: 90,
			MinGPUCount:     1,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
		},

		// MiaAI-Lab's DFlash2 production profile for the DGX Spark GB10.
		// Kept separate from the RTX PRO 6000 BKC: this is an arm64 image and
		// its Mamba/KV policy was measured on the 128 GB unified-memory system.
		Config{
			ID:       "qwen3-8-27b-nvfp4-bf16-lmhead-sglang-dflash2-gb10",
			Name:     "Qwen3.8 27B NVFP4 BF16 lm_head + DFlash2 (SGLang GB10)",
			Workload: WorkloadSGLang,
			ModelID:  "RadixArk/Qwen3.8-27B-NVFP4-BF16-LMHead",
			Image:    imageSGLangQwen38GB10DFlash2,
			Port:     "8888",
			ExtraArgs: strings.Join([]string{
				"sglang serve",
				"--trust-remote-code",
				"--revision 009632fef96dd349150baa780c984e62e70e91fe",
				"--served-model-name Qwen3.8-27B",
				"--tp-size 1",
				"--context-length 262144",
				"--mem-fraction-static 0.90",
				"--sleep-on-idle",
				"--attention-backend flashinfer",
				"--chunked-prefill-size 8192",
				"--disable-prefill-cuda-graph",
				"--kv-cache-dtype fp8_e4m3",
				"--mamba-ssm-dtype bfloat16",
				"--mamba-full-memory-ratio 4.21",
				"--mamba-radix-cache-strategy extra_buffer",
				"--max-mamba-cache-size 40",
				"--max-running-requests 10",
				"--speculative-algorithm DFLASH",
				"--speculative-draft-model-path z-lab/Qwen3.8-27B-DFlash2",
				"--speculative-draft-model-revision 50307d4c4cde6860d4eee73e2547cd786fe8e8a4",
				"--speculative-num-draft-tokens 8",
				"--reasoning-parser qwen3",
				"--tool-call-parser qwen3_coder",
				"--sampling-defaults model",
				"--enable-metrics",
				"--enable-cache-report",
			}, " "),
			Env: map[string]string{
				"SGLANG_OPT_MAMBA_SKIP_DECODE_LOCK": "0",
			},
			Volumes: hfMountDefault,
			Runtime: config.RuntimeOptions{
				IPCMode: "host",
				ShmSize: "32g",
			},
			Description: "Qwen3.8 27B NVFP4 with dense BF16 lm_head and DFlash2 on one DGX Spark GB10.",
			Source:      "MiaAI-Lab/Qwen3.8-27B-SGLang-DGX-Spark@9fb18edf (GB10 DFlash2 recipe)",
			Notes: []string{
				"Uses Mia's Sep 9 multi-arch SGLang image with the zombie-request fix; the digest resolves arm64 on GB10.",
				"Native 262,144-token context only: YaRN is incompatible with DFlash2 on this SGLang build.",
				"GB10 tuning uses 0.90 static memory, 8,192-token prefill chunks, BF16 Mamba state, a 40-slot Mamba pool, and 10 concurrent requests.",
				"DFlash2 requires extra_buffer on the validated GB10 image; do not substitute extra_buffer_lazy without a device-specific retest.",
				"The target and draft revisions are immutable. This BKC intentionally has GB10-only affinity.",
			},
			TargetDevices:   []string{DeviceGB10},
			MinVRAMGBPerGPU: 100,
			MinGPUCount:     1,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
		},

		// Default production profile validated on Finn's single RTX PRO 6000
		// Blackwell 96 GB. Retained as the packed-head rollback after the
		// BF16 lm_head checkpoint became the preferred upstream target.
		Config{
			ID:       "qwen3-8-27b-nvfp4-sglang-dflash2",
			Name:     "Qwen3.8 27B NVFP4 packed lm_head + DFlash2 (SGLang rollback)",
			Workload: WorkloadSGLang,
			ModelID:  "RadixArk/Qwen3.8-27B-NVFP4",
			Image:    imageSGLangQwen38DFlash2,
			Port:     "30000",
			ExtraArgs: strings.Join([]string{
				"sglang serve",
				"--trust-remote-code",
				"--revision 319f741cce68d7914884900c138a1fbb70a42f30",
				"--served-model-name Qwen3.8-27B",
				"--tp-size 1",
				"--context-length 262144",
				"--mem-fraction-static 0.85",
				"--max-running-requests 8",
				"--cuda-graph-max-bs-decode 8",
				"--mamba-radix-cache-strategy extra_buffer_lazy",
				"--mamba-ssm-dtype bfloat16",
				"--kv-cache-dtype fp8_e4m3",
				"--attention-backend flashinfer",
				"--chunked-prefill-size 2048",
				"--reasoning-parser qwen3",
				"--tool-call-parser qwen3_coder",
				`--default-chat-template-kwargs {"enable_thinking":false}`,
				"--speculative-algorithm DFLASH",
				"--speculative-draft-model-path incoai/Qwen3.8-27B-DFlash2",
				"--speculative-draft-model-revision dedf8df68adfb1afeaf7b7480c0a0243108177b4",
				"--speculative-num-draft-tokens 8",
				"--enable-metrics",
			}, " "),
			Volumes: hfMountDefault,
			Runtime: config.RuntimeOptions{
				IPCMode: "host",
				ShmSize: "32g",
			},
			Description: "Qwen3.8 27B packed-head NVFP4 with DFlash2 block-diffusion speculative decoding on one RTX PRO 6000 Blackwell, retained as the validated Finn rollback.",
			Source:      "SGLang Qwen3.8 RTX PRO 6000 recipe + production validation on Finn (2026-08-22)",
			Notes: []string{
				"Pinned target, DFlash2 drafter, and container revisions reproduce the validated Finn canary.",
				"Matched Finn results: 306.4 output tok/s for short code, 198.5 tok/s at exactly 32,768 prompt tokens, 961.7 tok/s aggregate at four-way, and 1,634.4 tok/s aggregate at eight-way concurrency.",
				"Validated 262,144-token context, OpenAI chat and Responses APIs, two-step tool calls, OpenCode2, native metrics, and long-context retrieval.",
				"The validated runtime allocated 117 target Mamba slots and a 1,048,431-token FP8 KV pool; concurrent requests share that pool.",
			},
			TargetDevices:   []string{DeviceRTXPRO6000},
			MinVRAMGBPerGPU: 90,
			MinGPUCount:     1,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
		},

		// Previous Finn production profile retained as a selectable rollback.
		// These revisions reproduce the NVFP4 deployment, not the earlier FP8
		// target used for the historical 298.4 tok/s microbenchmark.
		Config{
			ID:       "qwen3-8-27b-nvfp4-sglang-dspark",
			Name:     "Qwen3.8 27B NVFP4 + DSpark (SGLang rollback)",
			Workload: WorkloadSGLang,
			ModelID:  "RadixArk/Qwen3.8-27B-NVFP4",
			Image:    imageSGLangQwen38,
			Port:     "30000",
			ExtraArgs: strings.Join([]string{
				"sglang serve",
				"--trust-remote-code",
				"--revision 554ebba9b5f1b79dc11246341960360e6ef05ef4",
				"--served-model-name Qwen3.8-27B",
				"--tp-size 1",
				"--context-length 262144",
				"--mem-fraction-static 0.85",
				"--max-running-requests 3",
				"--max-mamba-cache-size 12",
				"--mamba-radix-cache-strategy extra_buffer_lazy",
				"--mamba-ssm-dtype bfloat16",
				"--kv-cache-dtype fp8_e4m3",
				"--attention-backend flashinfer",
				"--chunked-prefill-size 2048",
				"--cuda-graph-max-bs 3",
				"--reasoning-parser qwen3",
				"--tool-call-parser qwen3_coder",
				`--default-chat-template-kwargs {"enable_thinking":false}`,
				"--speculative-algorithm DSPARK",
				"--speculative-draft-model-path RadixArk/Qwen3.8-27B-DSpark",
				"--speculative-draft-model-revision 85ef153be924f17ce4bf62726954eeaa4a73e854",
				"--speculative-draft-attention-backend flashinfer",
				"--speculative-dspark-block-size 7",
				"--enable-metrics",
			}, " "),
			Volumes: hfMountDefault,
			Runtime: config.RuntimeOptions{
				IPCMode: "host",
				ShmSize: "32g",
			},
			Description: "Qwen3.8 27B NVFP4 with DSpark speculative decoding on one RTX PRO 6000 Blackwell, retained as Finn's 262K/3-request rollback BKC.",
			Source:      "SGLang Qwen3.8 recipe + production validation on Finn (2026-08-21)",
			Notes: []string{
				"Pinned target, draft-model, and container revisions reproduce the former live Finn NVFP4 deployment.",
				"Validated OpenAI chat/tool calls, native SGLang metrics, and 262,144-token context with at most three active requests.",
				"The historical 298.4 tok/s solo and 899.6 tok/s aggregate measurements used a Qwen/Qwen3.8-27B-FP8 target and do not characterize this NVFP4 rollback BKC.",
			},
			TargetDevices:   []string{DeviceRTXPRO6000},
			MinVRAMGBPerGPU: 90,
			MinGPUCount:     1,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
		},

		// Qwen3 dense small checkpoints — fit almost any consumer/workstation GPU.
		qwenSmallDense("qwen3-0-6b", "Qwen3 0.6B", "Qwen/Qwen3-0.6B", 6),
		qwenSmallDense("qwen3-1-7b", "Qwen3 1.7B", "Qwen/Qwen3-1.7B", 8),
		qwenSmallDense("qwen3-4b", "Qwen3 4B", "Qwen/Qwen3-4B", 12),
		qwenSmallDense("qwen3-8b", "Qwen3 8B", "Qwen/Qwen3-8B", 20),
		qwenSmallDense("qwen3-14b", "Qwen3 14B", "Qwen/Qwen3-14B", 32),
		qwenSmallDense("qwen3-32b", "Qwen3 32B", "Qwen/Qwen3-32B", 72),

		// Qwen3-30B-A3B dense MoE (A3B active).
		Config{
			ID:       "qwen3-30b-a3b",
			Name:     "Qwen3 30B A3B",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-30B-A3B",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 1",
				"--max-model-len 131072",
				"--reasoning-parser qwen3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3 30B A3B MoE, single-GPU Hopper/Blackwell default.",
			Source:          "vllm-project/recipes Qwen/Qwen3.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceA100_80, DeviceGB10},
			MinVRAMGBPerGPU: 64,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3 235B A22B BF16 (4x TP per the recipe).
		Config{
			ID:       "qwen3-235b-a22b",
			Name:     "Qwen3 235B A22B",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-235B-A22B",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"-tp 4",
				"--disable-log-requests",
				"--swap-space 32",
				"--distributed-executor-backend mp",
				"--max-num-batched-tokens 32768",
				"--max-model-len 32768",
				"--no-enable-prefix-caching",
				"--gpu-memory-utilization 0.8",
				"--reasoning-parser qwen3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3 235B A22B on 4xH200/B200.",
			Source:          "vllm-project/recipes Qwen/Qwen3.md",
			TargetDevices:   []string{DeviceH200, DeviceB200, DeviceH100_94},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     4,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3 235B A22B FP8.
		Config{
			ID:       "qwen3-235b-a22b-fp8",
			Name:     "Qwen3 235B A22B FP8",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-235B-A22B-FP8",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"-tp 4",
				"--disable-log-requests",
				"--swap-space 16",
				"--distributed-executor-backend mp",
				"--max-num-batched-tokens 32768",
				"--max-model-len 32768",
				"--no-enable-prefix-caching",
				"--gpu-memory-utilization 0.8",
				"--reasoning-parser qwen3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3 235B A22B FP8 on 4x Hopper/Blackwell GPUs.",
			Source:          "vllm-project/recipes Qwen/Qwen3.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH100_94, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     4,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
		},

		// Qwen3-Next 80B A3B Instruct BF16.
		Config{
			ID:       "qwen3-next-80b-a3b",
			Name:     "Qwen3-Next 80B A3B Instruct",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-Next-80B-A3B-Instruct",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 4",
				"--served-model-name qwen3-next",
				"--enable-prefix-caching",
				"--reasoning-parser qwen3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3-Next 80B A3B on 4x Hopper/Blackwell GPUs.",
			Source:          "vllm-project/recipes Qwen/Qwen3-Next.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     4,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3-Next 80B A3B Instruct FP8.
		Config{
			ID:       "qwen3-next-80b-a3b-fp8",
			Name:     "Qwen3-Next 80B A3B Instruct FP8",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-Next-80B-A3B-Instruct-FP8",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 4",
				"--enable-prefix-caching",
				"--reasoning-parser qwen3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "FP8 Qwen3-Next 80B on 4x Hopper/Blackwell GPUs.",
			Source:          "vllm-project/recipes Qwen/Qwen3-Next.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000},
			MinVRAMGBPerGPU: 40,
			MinGPUCount:     2,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
		},

		// Qwen3-Coder 480B A35B — 8x TP expert-parallel.
		Config{
			ID:       "qwen3-coder-480b-a35b",
			Name:     "Qwen3-Coder 480B A35B",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-Coder-480B-A35B-Instruct",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--max-model-len 32000",
				"--enable-expert-parallel",
				"--tensor-parallel-size 8",
				"--enable-auto-tool-choice",
				"--tool-call-parser qwen3_coder",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Flagship coding MoE on 8x Hopper or Blackwell.",
			Source:          "vllm-project/recipes Qwen/Qwen3-Coder-480B-A35B.md",
			TargetDevices:   []string{DeviceH100_94, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     8,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3-VL 235B A22B Instruct BF16.
		Config{
			ID:       "qwen3-vl-235b-a22b",
			Name:     "Qwen3-VL 235B A22B Instruct",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-VL-235B-A22B-Instruct",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 8",
				"--mm-encoder-tp-mode data",
				"--async-scheduling",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3-VL 235B A22B Instruct on 8x Hopper/Blackwell GPUs.",
			Source:          "vllm-project/recipes Qwen/Qwen3-VL.md",
			TargetDevices:   []string{DeviceH100_94, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     8,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3-VL 235B A22B Instruct FP8.
		Config{
			ID:       "qwen3-vl-235b-a22b-fp8",
			Name:     "Qwen3-VL 235B A22B Instruct FP8",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-VL-235B-A22B-Instruct-FP8",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 4",
				"--limit-mm-per-prompt.video 0",
				"--async-scheduling",
				"--gpu-memory-utilization 0.95",
				"--max-num-seqs 128",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "FP8 Qwen3-VL 235B, tensor-parallel 4 image-only.",
			Source:          "vllm-project/recipes Qwen/Qwen3-VL.md",
			TargetDevices:   []string{DeviceH100_80, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     4,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
		},

		// Qwen2.5-VL 7B.
		Config{
			ID:       "qwen2-5-vl-7b",
			Name:     "Qwen2.5-VL 7B Instruct",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen2.5-VL-7B-Instruct",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 1",
				"--max-model-len 32768",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen2.5-VL 7B Instruct — single-GPU default.",
			Source:          "vllm-project/recipes Qwen/Qwen2.5-VL.md",
			TargetDevices:   []string{DeviceRTX4090, DeviceRTX5090, DeviceL40S, DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10},
			MinVRAMGBPerGPU: 24,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen2.5-VL 72B BF16 (TP=4).
		Config{
			ID:       "qwen2-5-vl-72b",
			Name:     "Qwen2.5-VL 72B Instruct",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen2.5-VL-72B-Instruct",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--tensor-parallel-size 4",
				"--max-model-len 32768",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen2.5-VL 72B on 4x 80 GB GPUs per NVIDIA's recipe.",
			Source:          "vllm-project/recipes Qwen/Qwen2.5-VL.md",
			TargetDevices:   []string{DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     2,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
			Notes: []string{
				"TP should be >= 2 on 80 GB GPUs to avoid OOM.",
			},
		},

		// Qwen3-ASR.
		Config{
			ID:       "qwen3-asr-1-7b",
			Name:     "Qwen3-ASR 1.7B",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3-ASR-1.7B",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 1",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Compact Qwen3 ASR deployable on a single 16 GB+ GPU.",
			Source:          "vllm-project/recipes Qwen/Qwen3-ASR.md",
			TargetDevices:   []string{DeviceRTX4090, DeviceRTX5090, DeviceL40S, DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10},
			MinVRAMGBPerGPU: 16,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3Guard-Gen 0.6B.
		Config{
			ID:       "qwen3guard-gen-0-6b",
			Name:     "Qwen3Guard-Gen 0.6B",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3Guard-Gen-0.6B",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--host 0.0.0.0",
				"--max-model-len 32768",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Guardrails generator — runs on any modern NVIDIA/AMD GPU.",
			Source:          "vllm-project/recipes Qwen/Qwen3Guard-Gen.md",
			TargetDevices:   []string{DeviceRTX4090, DeviceRTX5090, DeviceL40S, DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10},
			MinVRAMGBPerGPU: 8,
			MinGPUCount:     1,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3.6 35B A3B.
		Config{
			ID:       "qwen3-6-35b-a3b",
			Name:     "Qwen3.6 35B A3B",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3.6-35B-A3B",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--tensor-parallel-size 8",
				"--max-model-len 262144",
				"--reasoning-parser qwen3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3.6 35B A3B on 8x Hopper/Blackwell (per the Qwen3.5 recipe).",
			Source:          "vllm-project/recipes Qwen/Qwen3.5.md",
			TargetDevices:   []string{DeviceH100_94, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     8,
			Quantization:    QuantBF16,
			Arch:            ArchHopper,
		},

		// Qwen3.6 27B VLM NVFP4 compressed-tensors baseline (Blackwell).
		Config{
			ID:       "qwen3-6-27b-nvfp4",
			Name:     "Qwen3.6-27B",
			Workload: WorkloadVLLM,
			ModelID:  "sakamakismile/Qwen3.6-27B-NVFP4",
			Image:    imageVLLMCU130_019,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--served-model-name Qwen3.6-27B",
				"--tensor-parallel-size 1",
				"--max-model-len 262144",
				"--max-num-seqs 2",
				"--kv-cache-dtype fp8",
				"--gpu-memory-utilization 0.90",
				"--limit-mm-per-prompt {\"image\":4,\"video\":0}",
				"--reasoning-parser qwen3",
				"--enable-auto-tool-choice",
				"--tool-call-parser qwen3_xml",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Compressed-tensors NVFP4 Qwen3.6 27B VLM on a single RTX PRO 6000 Blackwell; serves as Qwen3.6-27B with image input enabled.",
			Source:          "Hugging Face sakamakismile/Qwen3.6-27B-NVFP4 model card",
			TargetDevices:   []string{DeviceRTXPRO6000, DeviceB200},
			MinVRAMGBPerGPU: 96,
			MinGPUCount:     1,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
			Notes: []string{
				"Do not pass --quantization modelopt; this repo declares compressed-tensors in its model config.",
				"Uses the model card's production launch: 256K context, FP8 KV cache, max-num-seqs 2, and gpu-memory-utilization 0.90.",
				"Keeps image input enabled with an explicit multimodal prompt limit.",
				"Enables qwen3_xml tool calling for Qwen3.6 chat templates.",
				"The model card notes faster modelopt + MTP siblings exist, but this BKC intentionally targets this exact compressed-tensors repo.",
			},
		},

		// Qwen3.6 27B Text NVFP4 + MTP (Blackwell).
		Config{
			ID:       "qwen3-6-27b-text-nvfp4-mtp",
			Name:     "Qwen3.6-27B Text NVFP4 MTP",
			Workload: WorkloadVLLM,
			ModelID:  "sakamakismile/Qwen3.6-27B-Text-NVFP4-MTP",
			Image:    imageVLLMCU130_019,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"--trust-remote-code",
				"--quantization modelopt",
				"--language-model-only",
				"--tensor-parallel-size 1",
				"--max-model-len 262144",
				"--max-num-seqs 2",
				"--kv-cache-dtype fp8",
				"--gpu-memory-utilization 0.90",
				"--reasoning-parser qwen3",
				"--speculative-config.method qwen3_5_mtp",
				"--speculative-config.num_speculative_tokens 3",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "ModelOpt NVFP4 Qwen3.6 27B text-only checkpoint with Qwen3.5 MTP speculation for single-GPU Blackwell.",
			Source:          "Hugging Face sakamakismile/Qwen3.6-27B-Text-NVFP4-MTP model card",
			TargetDevices:   []string{DeviceB200, DeviceRTXPRO6000, DeviceGB10},
			MinVRAMGBPerGPU: 96,
			MinGPUCount:     1,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
			Notes: []string{
				"Uses dotted speculative-config arguments instead of JSON so Yokai passes them as clean argv tokens.",
				"Targets GB10 / DGX Spark, single RTX PRO 6000 Blackwell, and larger Blackwell GPUs.",
			},
		},

		// Qwen3.5 397B A17B FP8.
		Config{
			ID:       "qwen3-5-397b-a17b-fp8",
			Name:     "Qwen3.5 397B A17B FP8",
			Workload: WorkloadVLLM,
			ModelID:  "Qwen/Qwen3.5-397B-A17B-FP8",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"-dp 8",
				"--enable-expert-parallel",
				"--language-model-only",
				"--reasoning-parser qwen3",
				"--enable-prefix-caching",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "Qwen3.5 397B A17B FP8 with data parallel expert routing.",
			Source:          "vllm-project/recipes Qwen/Qwen3.5.md",
			TargetDevices:   []string{DeviceH100_94, DeviceH200, DeviceB200},
			MinVRAMGBPerGPU: 80,
			MinGPUCount:     8,
			Quantization:    QuantFP8,
			Arch:            ArchHopper,
		},

		// Qwen3.5 397B A17B NVFP4 (Blackwell).
		Config{
			ID:       "qwen3-5-397b-a17b-nvfp4",
			Name:     "Qwen3.5 397B A17B NVFP4",
			Workload: WorkloadVLLM,
			ModelID:  "nvidia/Qwen3.5-397B-A17B-NVFP4",
			Image:    imageVLLMStable,
			Port:     "8000",
			ExtraArgs: strings.Join([]string{
				"-dp 4",
				"--enable-expert-parallel",
				"--language-model-only",
				"--reasoning-parser qwen3",
				"--enable-prefix-caching",
			}, " "),
			Volumes:         hfMountDefault,
			Runtime:         runtimeDefault,
			Description:     "NVFP4 Blackwell deployment of Qwen3.5 397B A17B.",
			Source:          "vllm-project/recipes Qwen/Qwen3.5.md",
			TargetDevices:   []string{DeviceB200},
			MinVRAMGBPerGPU: 180,
			MinGPUCount:     4,
			Quantization:    QuantNVFP4,
			Arch:            ArchBlackwell,
		},
	)
}

// qwenSmallDense returns a BKC config for a compact Qwen3 dense checkpoint.
// Every small Qwen3 model shares the same vLLM launch shape, so we synthesise
// the Config to cut down on repetition.
func qwenSmallDense(id, name, modelID string, minVRAMGB float64) Config {
	return Config{
		ID:       id,
		Name:     name,
		Workload: WorkloadVLLM,
		ModelID:  modelID,
		Image:    imageVLLMStable,
		Port:     "8000",
		ExtraArgs: strings.Join([]string{
			"--trust-remote-code",
			"--tensor-parallel-size 1",
			"--max-model-len 32768",
			"--reasoning-parser qwen3",
		}, " "),
		Volumes:         hfMountDefault,
		Runtime:         runtimeDefault,
		Description:     name + " — single-GPU default.",
		Source:          "vllm-project/recipes Qwen/Qwen3.md",
		TargetDevices:   []string{DeviceRTX4090, DeviceRTX5090, DeviceL40S, DeviceA100_80, DeviceH100_80, DeviceH200, DeviceB200, DeviceRTXPRO6000, DeviceGB10},
		MinVRAMGBPerGPU: minVRAMGB,
		MinGPUCount:     1,
		Quantization:    QuantBF16,
		Arch:            ArchHopper,
	}
}
